name: Update Winget Manifest

on:
  release:
    types: [published]

jobs:
  update:
    runs-on: windows-latest

    steps:
    - name: Install winget-create
      run: |
        Invoke-WebRequest -Uri 'https://aka.ms/wingetcreate/latest' -OutFile 'wingetcreate.exe'

    - name: Update Winget Manifest
      run: |
        $assets = '${{ toJson(github.event.release.assets) }}' | ConvertFrom-Json
        $url = ($assets | Where-Object { $_.name -eq "det.exe" }).browser_download_url
        .\wingetcreate.exe update --submit "Determined AI" --token "${{ secrets.WINGET_TOKEN }}" -urls $url --version ${{ github.event.release.tag_name }} DeterminedAI.CLI