name: Update Winget Manifest

on:
  release:
    types: [published]

jobs:
  update:
    runs-on: windows-latest

    steps:
    - name: Install winget-create
      run: |
        Invoke-WebRequest -Uri 'https://aka.ms/wingetcreate/latest' -OutFile 'wingetcreate.exe'

    - name: Update Winget Manifest
      run: |
        .\wingetcreate.exe update --submit "Determined AI" --token "${{ secrets.WINGET_TOKEN }}" -urls ${{ github.event.release.zipball_url }} --version ${{ github.event.release.tag_name }} DeterminedAI.CLI